---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: koap
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: koap
rules:
  # Listen to ConfigMaps
  - apiGroups: [""]
    resources: [configmaps]
    verbs: [list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: koap
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: koap
subjects:
  - kind: ServiceAccount
    name: koap