on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: koap-ui

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm ci
    - run: npm run build
    - run: npm test
  